feat: add serverless
VlPan/shop-angular-cloudfront pull request #1
Opened 2022-10-11 11:13 UTC by VlPan

2022-10-11 22:46 UTC, kumbas commented
👍

2022-10-13 20:42 UTC, SlavaJSFE requested changes

2022-10-13 20:42 UTC, SlavaJSFE commented on serverless.yml
> +  runtime: nodejs12.x
Here is good place to specify deploy region, for example "region: eu-west-1"

2022-10-13 20:42 UTC, SlavaJSFE commented on README.md
> +S3 Website: https://d31btok0tze5tb.cloudfront.net/
There is not S3 bucket link! Please provide one.

2023-02-20 08:13 UTC, closed without merging